// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Praktik_Work_2.ViewModels;
using System;
using System.Collections.Generic;

namespace Praktik_Work_2.Models;

public partial class DataSoldier
{
    public int DataId { get; set; }

    public int SoldierId { get; set; }

    public string ParentsAdress { get; set; }

    public string CharacterTraits { get; set; }

    public string AttitudeService { get; set; }

    public decimal PhoneNumber { get; set; }

    public string Education { get; set; }

    public string CitizenProfession { get; set; }

    public virtual Soldier Soldier { get; set; }

    public DataSoldier ShallowCopy()
    {
        return (DataSoldier)this.MemberwiseClone();
    }

    public DataSoldier CopyFromSoldier(DataSoldier dataSoldier)
    {
        SoldiersViewModel vmSolder = new SoldiersViewModel();
        int soldId = 0;
        foreach (var soldier in vmSolder.ListSolder)
        {
            if (dataSoldier.SoldierId == soldier.SoldierId)
            {
                soldId = soldier.SoldierId;
                break;
            }
        }
        if (soldId != 0)
        {
            this.DataId = dataSoldier.DataId;
            this.SoldierId = soldId;
            this.ParentsAdress = dataSoldier.ParentsAdress;
            this.CharacterTraits = dataSoldier.CharacterTraits;    
            this.AttitudeService = dataSoldier.AttitudeService;
            this.PhoneNumber = dataSoldier.PhoneNumber;
            this.Education = dataSoldier.Education;
            this.CitizenProfession = dataSoldier.CitizenProfession;
        }
        return this;
    }
}